name: "bert_pt"
platform: "pytorch_libtorch"
max_batch_size: 0
input {
    name: "input__0"
    data_type: TYPE_INT32
    dims: [ -1 ]
  }
output {
    name: "output__0"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
version_policy: { latest { num_versions : 1 }}
